# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       libusb1

# >> macros
# << macros
%define keepstatic 1

Summary:    A library which allows userspace access to USB devices
Version:    1.0.9
Release:    1
Group:      System/Libraries
License:    LGPLv2+
URL:        http://libusb.wiki.sourceforge.net/Libusb1.0
Source0:    http://downloads.sourceforge.net/libusb/libusb-%{version}.tar.bz2
Source100:  libusb1.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  doxygen

%description
This package provides a way for applications to access USB devices. Note that
this library is not compatible with the original libusb-0.1 series.


%package static
Summary:    Static development files for libusb
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description static
This package contains static libraries to develop applications that use libusb1.

%package devel
Summary:    Development files for libusb
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
This package contains the header files, libraries  and documentation needed to
develop applications that use libusb1.



%prep
%setup -q -n libusb-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure 
make %{?jobs:-j%jobs}

# >> build post
pushd doc
make docs
popd
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
rm -f $RPM_BUILD_ROOT%{_libdir}/*.la

# << install post


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING README NEWS ChangeLog
%{_libdir}/*.so.*
# << files

%files static
%defattr(-,root,root,-)
# >> files static
%{_libdir}/*.a
# << files static

%files devel
%defattr(-,root,root,-)
# >> files devel
%doc doc/html examples/*.c
%{_libdir}/pkgconfig/libusb-1.0.pc
%{_includedir}/*
%{_libdir}/*.so
# << files devel
